# Generated by Django 5.0 on 2024-06-01 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PM2_5', models.FloatField()),
                ('PM10', models.FloatField()),
                ('CO2', models.FloatField()),
                ('timestamp', models.DateField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='Sensors.sensor')),
            ],
            options={
                'verbose_name': ('Data',),
                'verbose_name_plural': 'Data',
            },
        ),
    ]
